name: mvcnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8  # Stable and tested version for machine learning libraries
  - numpy
  - scipy
  - matplotlib
  - pillow
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
    - torchsummary
    - jupyterlab  # Optional, for running Jupyter notebooks
